### ISSUE TITLE
OAuth 인증 기능

### ISSUE THREAD

**Issue by skyoo2003** [itslaves/rentalgames-server#2]
세션 ID 는 브라우저 쿠키에 저장해서 사용
세션은 레디스에 저장.

최초 인증 후 사용자 DB에 없는 상황이면, 인증 쪽에서 제공해준 정보 (email, nickname 등) 으로 생성 후 회원가입 페이지로 리다이렉션 (front 쪽과 같이 작업할 부분도 있을듯함)

Ref. https://tansfil.tistory.com/60?category=255594

**Comment by skyoo2003** [comment]
### To-do list

- ~클라 쪽에서 Access_Token 전달 받아서 리소스 서버에 요청해서 사용자 정보 가져오기~
  - 인증 실패하면 `status: error` 로 리턴
- [x] 가져온 유니크 키로 사용자 정보 MySQL 에 사용자 조회
  - [x] 테이블에 없으면 `status: join` + 프로필 정보를 같이 리턴
  - [x] 있으면 Redis 세션에 저장하고 `status: ok` 로 리턴 ( 레디스 환경 셋팅 전에는 로그 찍기 )

API 응답 코드는 한번 살펴보고 재정의

**Comment by skyoo2003** [comment]
어제 이야기 했던 내용 정리

- 레디스 세션 스토어는 직접 구현해서 사용하는 쪽으로 진행
- 인증은 클라쪽에서 하지 않고 서버 쪽에서 처리하도록 진행
  - UI 쪽은 벤더별로 인증 URL 을 링크로 하는 버튼만 제공
    - 단, 인증 URL 에는 clientId, state 등을 채워줘야하는 부분이 있으므로 API 서버 쪽에 요청해서 링크를 동적으로 생성한다 (ex) `[{"image": "xxx", "link": "xxx", "vendor": "kakao"}]`
  - 인증 후 oauth callback 은 벤더별로 URL Path 구분
  - 인증 토큰 요청 후 처리
    - 1) 인증이 실패했을 때 -> Error 페이지로 리다이렉션
    - 2) 인증이 성공했으나 계정 정보가 MySQL DB 에 존재하지 않을 때 -> OAuth ResourceServer 로 사용자 정보 요청 후 벤더에서 제공하는 사용자 정보를 포함해서 Join 페이지로 리다이렉션
    - 3) 인증이 성공했으나 계정 정보가 이미 DB 에 존재할 때 -> 세션에 access_token, refresh_token 등 사용자 인증 정보를 세션에 저장하고 Main 페이지로 리다이렉션
